feat: create mod card template
nhcommunity/homepage pull request #13
Opened 2021-05-17 22:39 UTC by DennaGrey

# Pull Request
## Description:
Creating a template for the moderator's "cards" on the community page.
## Related Issue:

Closes #XXXXX

2021-05-20 05:01 UTC, nhcarrigan commented
Remind me to review this in the morning. 💜

2021-05-20 18:55 UTC, nhcarrigan requested changes
![image](https://user-images.githubusercontent.com/63889819/119033628-49bd2c00-b962-11eb-862c-b2d380ce76bc.png)

Couple of tiny tweaks to give some space at the top and bottom. Thoughts?

2021-05-20 18:55 UTC, nhcarrigan commented on templates/moderator-card.html
> +    border-radius: 15px;
```suggestion
    border-radius: 15px;
    padding-top: 3px;
    padding-bottom: 10px;
```

2021-05-21 04:13 UTC, Skyhero-admin commented on templates/moderator-card.html
> +    border-radius: 15px;
looks good 👍

2021-05-21 15:25 UTC, DennaGrey commented on templates/moderator-card.html
> +    border-radius: 15px;
I like the bottom, but i kind of intentionally wanted it to touch at the top.

2021-05-21 15:45 UTC, nhcarrigan commented on templates/moderator-card.html
> +    border-radius: 15px;
Works for me then 💜

2021-05-21 15:45 UTC, nhcarrigan approved these changes

2021-05-25 14:03 UTC, merged