Back-end improvements and end-user improvements
nhcommunity/homepage pull request #22
Opened 2021-07-16 01:58 UTC by Panquesito7

# Pull Request

## Description

- Align some texts to the center.
- Add favicon to the website. The logo is the one shown on the website's bottom. 
- Add `Nicholas Carrigan` in parentheses after Nicholas' nickname at the bottom.

2021-07-16 02:45 UTC, nhcarrigan commented
Rather than wrapping the h2 elements in p elements, we should use CSS to style the h2 elements directly. 

AFAIK, wrapping headers in paragraph elements isn't semantic HTML.

2021-07-16 03:23 UTC, Panquesito7 commented
> we should use CSS to style the h2 elements directly

Done. 🙂

2021-07-18 16:46 UTC, nhcarrigan requested changes

2021-07-18 16:46 UTC, nhcarrigan commented on index.html
> +    </p>
This one should also not be within a `p` tag.

2021-07-18 16:46 UTC, nhcarrigan commented on index.html
> -    <li><a href="#becca">Becca</a></li>
We should leave this here - I believe we had plans to add a brief section for this.

2021-07-20 19:13 UTC, Vyvy-vi reviewed
LGTM!
I'm wondering, if the favicon added here might conflict with the favicon added by #18 ?

2021-07-20 19:30 UTC, Panquesito7 commented
> might conflict with the favicon added by #18

I'm not so sure. That PR makes a lot of changes and modifies lots of stuff. IMO, it seems too much to simply add a favicon. 🤷‍♂️

2021-07-22 19:27 UTC, nhcarrigan approved these changes
I think I'm good with this.

2021-07-27 20:24 UTC, merged