Add NHcommunity Moderators
nhcommunity/homepage pull request #28
Opened 2021-09-17 07:01 UTC by Evavic44

## Description
- Recognize moderators
- Add Moderators Section
- 

Add the moderators of NHcommunity

## Related Issue
#3 #5 

Closes #3

2021-09-17 07:58 UTC, Akshu-on-github commented on public/index.css
> +   } */
Should we remove this if it has been commented out?

2021-09-17 08:05 UTC, Akshu-on-github requested changes
Here are a few things that I noticed:
- The moderators' social media links aren't filled in - might want to add those in before merging
- The moderators' pictures are uploaded to the branch - I'd suggest using a link to the GitHub Avatar so that it reflects any changes to the profile picture that may occur

2021-09-17 09:20 UTC, Evavic44 commented on public/index.css
> +   } */
Removed. https://github.com/nhcommunity/homepage/pull/28/commits/2921eb1f09ed50a7c019b2fd365ef58055d9cee7

2021-09-17 09:24 UTC, Evavic44 commented
- Adding the links can be a `#goodfirstissue` for the community.
- That's a good idea. Can still be a good issue for the community. What do you think?

2021-09-17 13:48 UTC, Panquesito7 commented on index.html
> +                  <p>Maintainer @TheAlgorithms, @devicons</p>
```suggestion
                  <p>Maintainer @TheAlgorithms, @devicons, and 10+ open-source communities</p>
```

2021-09-17 13:48 UTC, Panquesito7 commented on public/index.css
> +}
Missing endline.
```suggestion
}

```

2021-09-17 14:16 UTC, Akshu-on-github commented
> * Adding the links can be a `#goodfirstissue` for the community.
> * That's a good idea. Can still be a good issue for the community. What do you think?

Sounds good to me 👍

2021-09-17 14:18 UTC, nhcarrigan commented
For the record, not all of our Discord moderators are on GitHub.

2021-09-17 14:20 UTC, nhcarrigan requested changes
Here's my thoughts:

Rather than listing all of the information on the home page, I think we should have a cleaner display there with each moderator's:

- username
- avatar
- position in our org (moderator, support, developer)

And the entire card can be wrapped in a link to a page that contains their full information, using the moderator card provided in `templates`.

2021-09-17 15:34 UTC, Evavic44 commented
> 
> 
> For the record, not all of our Discord moderators are on GitHub.

Yeah, you mentioned that. They can be added subsequently on other PR's if possible.

2021-09-17 15:51 UTC, Evavic44 commented
I didn't notice there was a moderators file and I'm also kinda confused. Do you mean the individual cards of the moderators should be joined together and made a single link that redirects to the `moderators-card` page? @nhcarrigan 💡

2021-09-17 15:55 UTC, nhcarrigan commented
![image](https://user-images.githubusercontent.com/63889819/133817814-d8b8fbad-5ceb-493a-8faa-32aa4b9c7cf0.png)

I am thinking each mod gets a box like this on the home page, and clicking this box leads to the moderator's specific page (we can put these under `/mods/<username.html>`). Those moderator-specific pages would each use the template in `/templates` to display the moderator's information.

2021-09-17 16:49 UTC, Evavic44 commented
> 
> 
> ![image](https://user-images.githubusercontent.com/63889819/133817814-d8b8fbad-5ceb-493a-8faa-32aa4b9c7cf0.png)
> 
> I am thinking each mod gets a box like this on the home page, and clicking this box leads to the moderator's specific page (we can put these under `/mods/<username.html>`). Those moderator-specific pages would each use the template in `/templates` to display the moderator's information.
> 
> The subtext would be the member's role in our community - `support`, `moderator`, `developer`

Oh... that is clearer now. Will make the necessary changes. Thanks. 👍🏾

2021-09-18 03:03 UTC, Evavic44 commented
Changes implemented.
 
## Things to note
- Community roles may require updating since it was not specified what role each moderator has. 
- Discord moderators will need to be identified to be added.

2021-09-19 14:38 UTC, Panquesito7 reviewed
These suggestions do not have to be accepted 🙂 if you like them, you can implement them.

2021-09-19 14:38 UTC, Panquesito7 commented on index.html
> +                  <h3>Eddiejaoude</h3>
```suggestion
                  <h3>Eddie Jaoude</h3>
```

2021-09-19 14:38 UTC, Panquesito7 commented on index.html
> +                  <h3>Nhcarrigan</h3>
```suggestion
                  <h3>Nicholas Carrigan</h3>
```

2021-09-19 14:38 UTC, Panquesito7 commented on index.html
> +                  <h3>Vyvy-vi</h3>
```suggestion
                  <h3>Vyom Jain</h3>
```

2021-09-19 14:38 UTC, Panquesito7 commented on index.html
> +                  <h3>Panquesito7</h3>
```suggestion
                  <h3>David Leal</h3>
```

2021-09-19 14:38 UTC, Panquesito7 commented on index.html
> +                  <h3>Kaiwalyakoparkar</h3>
```suggestion
                  <h3>Kaiwalya Koparkar</h3>
```

2021-09-19 15:38 UTC, nhcarrigan commented
I'm going to go ahead and rebase this and merge it in so I can play with the layout some more.

2021-09-19 15:42 UTC, nhcarrigan approved these changes
Looks good to me.

2021-09-19 15:42 UTC, merged

2021-09-19 15:42 UTC, nhcarrigan commented
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

2021-09-19 19:21 UTC, Evavic44 commented
> 
> ## Thank You
> 
> Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.
> 
> Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

Awesome. Thank you, Nick. 😎