feat: Add Open Graph Meta tags
nhcommunity/homepage pull request #39
Opened 2021-11-30 18:11 UTC by Panquesito7

# Pull Request

## Description

- Add Open Graph Meta tags.

2021-11-30 18:17 UTC, nhcarrigan requested changes

2021-11-30 18:17 UTC, nhcarrigan commented on index.html
>      />
This one needs to be removed since you've added one on line 17.

2021-11-30 18:17 UTC, nhcarrigan commented on index.html
> +    <meta property="og:image" content="https://user-images.githubusercontent.com/51391473/144103613-229d1856-7815-4c14-b43c-229646bc66fb.png" />
```suggestion
    <meta property="og:image" content="https://cdn.nhcarrigan.com/content/avatars/nhcommunity.png" />
```

CDN link.

2021-11-30 18:17 UTC, nhcarrigan commented on index.html
> +    <meta property="og:description" content="We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way." />
```suggestion
    <meta property="og:description" content="We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way." />
    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:creator" content="@nhcarrigan" />
```
Let's enable the twitter embed too 🙂

2021-11-30 19:30 UTC, nhcarrigan approved these changes
Looks good to me!

2021-11-30 19:31 UTC, merged

2021-11-30 19:31 UTC, nhcarrigan commented
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

2021-12-01 03:18 UTC, krishguptadev reviewed
LGTM!