Restore timero photo
nhcommunity/homepage pull request #64
Opened 2022-08-22 17:33 UTC by NerdyChara

# Pull Request

## Description

Updates Timero's link to use the current DIscord url. Eventually I want to ensure that all images are from the app itself but for now it's solid. 
## Related Issue

Closes #XXXXX

2022-08-22 18:43 UTC, naomi-lgbt requested changes

2022-08-22 18:43 UTC, naomi-lgbt commented on index.html
> +              src="https://cdn.discordapp.com/avatars/342472606257250314/239cbf0523a88afecce5f4ce6e3c8dd2.webp"
Since we are using the Discord link, we don't need to upload the photo in this PR.

2022-08-22 21:36 UTC, Panquesito7 approved these changes
Looks good, apart from what Naomi said. Thanks. 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Maintainable

2022-08-26 16:05 UTC, NerdyChara commented on index.html
> +              src="https://cdn.discordapp.com/avatars/342472606257250314/239cbf0523a88afecce5f4ce6e3c8dd2.webp"
I thought I deleted it on my branch. Let me go check it. ._.

2022-08-26 16:06 UTC, NerdyChara commented on index.html
> +              src="https://cdn.discordapp.com/avatars/342472606257250314/239cbf0523a88afecce5f4ce6e3c8dd2.webp"
Okay there it is. It's gone now.

2022-08-26 19:51 UTC, naomi-lgbt approved these changes
Awesome let's get this in.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-08-26 20:00 UTC, Panquesito7 approved these changes
Amazing! Thanks. 🚀


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Efficient

2022-08-26 20:21 UTC, merged

2022-08-26 20:21 UTC, naomi-lgbt commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)