Add line-height to improve line spacing between texts
nhcommunity/homepage pull request #66
Opened 2022-10-02 05:45 UTC by muditchoudhary

# Pull Request

## Description
Text inside some section like our community, gaming etc. are too congested. I've added some line height to add some  space between the texts.

## Related Issue

Closes #65

2022-10-07 02:22 UTC, muditchoudhary commented
Hey, @naomi-lgbt could please review this PR?
Thank you!!

2022-10-09 22:12 UTC, naomi-lgbt requested changes
Exact units aren't ideal for responsiveness - let's pass a raw number to `line-height` and let it calculate based on the font size.

2022-10-09 22:12 UTC, naomi-lgbt commented on public/index.css
> +    line-height: 25px;
```suggestion
    line-height: 1.5;
```

2022-10-09 22:12 UTC, naomi-lgbt commented on public/index.css
> +    line-height: 25px;
```suggestion
    line-height: 1.5;
```

2022-10-10 14:01 UTC, muditchoudhary commented
@naomi-lgbt fixed!!

2022-10-10 19:29 UTC, naomi-lgbt approved these changes
banger pr, thanks for contributing!

2022-10-10 19:29 UTC, merged

2022-10-10 19:30 UTC, naomi-lgbt commented
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt)