Added some info to the page
nhcommunity/homepage pull request #8
Opened 2021-05-09 05:24 UTC by Skyhero-admin

# Pull Request

It would be good to get some feedback on the current information for the landing page
I've some info in the index.html file here https://github.com/Skyhero-admin/homepage

If you have any suggestions to add or if something doesn't seem right and should be removed then please do let me know sweat_smile

Also It's still not styled yet so I need some ideas for it

2021-05-09 13:17 UTC, nhcarrigan requested changes
This is looking good - just a couple of nitpicks. 🙂

2021-05-09 13:17 UTC, nhcarrigan commented on index.html
> +        <b>We also have a lot of other fun activity's happenning every now then</b>
We should not use `<br>` tags to create spacing as this is an accessibility concern.

2021-05-09 13:17 UTC, nhcarrigan commented on index.html
> +      </h3>
I'm not sure this should be an `h3`.

2021-05-09 13:17 UTC, nhcarrigan commented on index.html
> +      I am a firm believer in open-source. All of my project files are available on GitHub, and I am open to Pull Requests and suggestions on all of them. If you would like to contribute, you can acc
Again, we want to avoid `br` tags.

2021-05-09 14:29 UTC, Skyhero-admin commented on index.html
> +        <b>We also have a lot of other fun activity's happenning every now then</b>
Ohk
I'll fix that

2021-05-09 15:10 UTC, nhcarrigan approved these changes
Looks good to me - we're off to a great start now :D

2021-05-10 14:29 UTC, Skyhero-admin commented
Should I add some info about Becca here ?
And can I start adding some styling and images if that's okay

2021-05-10 14:34 UTC, nhcarrigan commented
Feel free to add the styling yes!

I don't think we need information for Becca since she's not necessarily a community project.

2021-05-10 14:35 UTC, Skyhero-admin commented
ohk

2021-05-12 03:00 UTC, starlightknown requested changes

2021-05-12 03:00 UTC, starlightknown commented on index.html
> +        <b>We also have a lot of other fun activity's happenning every now then</b>
shouldn't it be `activities` and not `activity's` ?

2021-05-12 03:00 UTC, starlightknown commented on index.html
> +      <h2>Who is Nhcarrigan ?</h2>
We can add the same picture of Nick here too like the picture above and then the who is NH part

2021-05-12 03:00 UTC, starlightknown commented on index.html
> +      <p class="para">I am a web developer focusing on the MEAN stack with a love for TypeScript. Development is a passion of mine, which began with the FreeCodeCamp curriculum on 15 April 2020. In D
change `MEAN` to `MERN`

2021-05-12 03:09 UTC, nhcarrigan commented on index.html
> +      <p class="para">I am a web developer focusing on the MEAN stack with a love for TypeScript. Development is a passion of mine, which began with the FreeCodeCamp curriculum on 15 April 2020. In D
Nope. I'm a `MEAN` stack dev. 🙂

2021-05-12 03:10 UTC, nhcarrigan commented on index.html
> +      <h2>Who is Nhcarrigan ?</h2>
We can use this link `https://cdn.nhcarrigan.com/content/profile.jpg`

2021-05-12 03:10 UTC, nhcarrigan commented on index.html
> +        <b>We also have a lot of other fun activity's happenning every now then</b>
Yes.

2021-05-12 03:52 UTC, starlightknown commented on index.html
> +      <p class="para">I am a web developer focusing on the MEAN stack with a love for TypeScript. Development is a passion of mine, which began with the FreeCodeCamp curriculum on 15 April 2020. In D
wait that's there? It's MEAN? MEAN and MERN are different?

2021-05-12 04:51 UTC, nhcarrigan commented on index.html
> +      <p class="para">I am a web developer focusing on the MEAN stack with a love for TypeScript. Development is a passion of mine, which began with the FreeCodeCamp curriculum on 15 April 2020. In D
MEAN is MongoDB, Express, Angular, and Node
MERN is MongoDB, Express, React, and Node

2021-05-12 04:53 UTC, starlightknown commented on index.html
> +      <p class="para">I am a web developer focusing on the MEAN stack with a love for TypeScript. Development is a passion of mine, which began with the FreeCodeCamp curriculum on 15 April 2020. In D
Got it

2021-05-12 06:01 UTC, Skyhero-admin commented on index.html
> +      <h2>Who is Nhcarrigan ?</h2>
Oh yes
Thanks for pointing out

2021-05-12 06:02 UTC, Skyhero-admin commented on index.html
> +        <b>We also have a lot of other fun activity's happenning every now then</b>
Oh yes,
thanks for pointing out

2021-05-12 08:58 UTC, Skyhero-admin commented
Everyone please suggest some colors for the site  😅

2021-05-12 09:00 UTC, Skyhero-admin commented
And what kind of image can we use for the as background for #welcome

2021-05-13 01:14 UTC, Evavic44 commented
> Everyone please suggest some colors for the site 😅
![Nhcommunity Colors](https://user-images.githubusercontent.com/62628408/118063334-cfecd780-b390-11eb-915e-125bb4e6b6fd.png)

2021-05-13 03:04 UTC, starlightknown commented
> > Everyone please suggest some colors for the site sweat_smile
> 
> I generated this pallet using the community profile photo as inspiration. What do you all think? sunglasses
> ![Nhcommunity Colors](https://user-images.githubusercontent.com/62628408/118063334-cfecd780-b390-11eb-915e-125bb4e6b6fd.png)

cool!

2021-05-13 03:06 UTC, starlightknown commented
I think we can add about Nh section liked to the nav bar, here's the PR for it @Skyhero-admin 
#9

2021-05-13 08:46 UTC, Skyhero-admin commented
> I think we can add about Nh section liked to the nav bar, here's the PR for it @Skyhero-admin
> #9

oh looks good 👍

2021-05-13 08:48 UTC, Skyhero-admin commented
> > Everyone please suggest some colors for the site sweat_smile
> 
> I generated this pallet using the community profile photo as inspiration. What do you all think? sunglasses
> ![Nhcommunity Colors](https://user-images.githubusercontent.com/62628408/118063334-cfecd780-b390-11eb-915e-125bb4e6b6fd.png)

thanks for this 👍
I will try adding these

2021-05-13 14:55 UTC, Evavic44 commented
> > > Everyone please suggest some colors for the site sweat_smile
> > 
> > 
> > I generated this pallet using the community profile photo as inspiration. What do you all think? sunglasses
> > ![Nhcommunity Colors](https://user-images.githubusercontent.com/62628408/118063334-cfecd780-b390-11eb-915e-125bb4e6b6fd.png)
> 
> thanks for this 👍

I would like to add it to the `CSS` file as a comment for easy access.

2021-05-13 15:44 UTC, Skyhero-admin commented
> > > > Everyone please suggest some colors for the site sweat_smile
> > > 
> > > 
> > > I generated this pallet using the community profile photo as inspiration. What do you all think? sunglasses
> > > ![Nhcommunity Colors](https://user-images.githubusercontent.com/62628408/118063334-cfecd780-b390-11eb-915e-125bb4e6b6fd.png)
> > 
> > 
> > thanks for this +1
> 
> I would like to add it to the `CSS` file as a comment for easy access.

Sure that would be cool
You should try adding it

2021-05-13 15:52 UTC, Skyhero-admin commented
![about nick](https://user-images.githubusercontent.com/74371107/118151324-201b7680-b431-11eb-9ac4-d41a30ff266c.png)
Should I keep the background for this section as white since the picture has a white background and it stands out ?
Any ideas

2021-05-14 02:27 UTC, nhcarrigan commented
I can re-upload the transparent version to my CDN so it'll fit that colour better.

2021-05-14 03:09 UTC, nhcarrigan commented
Hey @Skyhero-admin I gave this a rebase after landing a couple of PRs.

If you're working on this locally, you'll need to update your local files with:
```bash
git fetch origin
git reset --hard origin/main
```

2021-05-14 04:23 UTC, Skyhero-admin commented
> s locally, you'll need to update your local files with:

ohk,
Understood

2021-05-20 04:25 UTC, Skyhero-admin commented
Some links are yet to be added , should I add them now or can we add them later ?

2021-05-20 04:26 UTC, nhcarrigan commented
We can always add things later on - this PR doesn't have to accomplish everything at once. 🙂

2021-05-20 04:27 UTC, Skyhero-admin commented
ohk

2021-05-21 09:42 UTC, Vyvy-vi commented on index.html
> +      <p class="para">I am a web developer focusing on the MEAN stack with a love for TypeScript. Development is a passion of mine, which began with the FreeCodeCamp curriculum on 15 April 2020. In D
Nick is MEARN? xD

2021-05-21 10:26 UTC, Vyvy-vi reviewed
Maybe we should add some space at bottom of the page?

2021-05-21 10:26 UTC, Vyvy-vi commented on index.html
> +        A love of gaming is something a lot of people share, and we’d love to share it with you! Often playing rounds of Among us, as well as a plethora of other games we are always looking to expand
```suggestion
        A love for gaming is something a lot of people share, and we’d love to share it with you! Often playing rounds of Among us, as well as a plethora of other games we are always looking to expand our community of players.
```

2021-05-21 10:30 UTC, shreyas44 commented on index.html
> +        We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member <b><a href="#whoi
```suggestion
        We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member <b><a href="#whoisNH">NhCarrigan</a></b> is committed to helping members of the <a href="https://freecodecamp.org"><b>freeCodeCamp</b></a> community, as well as <a href="https://eddiehub.org"><b>EddieHub</b></a> by providing further support to any who need it. We have a staff of moderators who share this vision, come meet them here (link) and check out some of their amazing projects!
```
Add links to FCC and EddieHub?

2021-05-21 10:39 UTC, Skyhero-admin commented on index.html
> +        We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member <b><a href="#whoi
Should I put their website links?

2021-05-21 10:41 UTC, Skyhero-admin commented on index.html
> +        A love of gaming is something a lot of people share, and we’d love to share it with you! Often playing rounds of Among us, as well as a plethora of other games we are always looking to expand
Oh
thanks for pointing it out
I had missed it 😅

2021-05-21 10:42 UTC, Skyhero-admin commented on index.html
> +      <li><a href="#whoisNH">About NhCarrigan</a></li>
Ohk I will fix that

2021-05-21 10:47 UTC, shreyas44 commented on index.html
> +        We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member <b><a href="#whoi
Yep!

2021-05-21 10:48 UTC, Skyhero-admin commented on index.html
> +        We’re a group of members committed to providing a safe, and comfortable space for anyone to try their hand at coding, and have some fun along the way. As our founding member <b><a href="#whoi
ohk 👍

2021-06-03 09:24 UTC, Skyhero-admin commented
should I fix something else ?

2021-06-03 15:56 UTC, DennaGrey commented on index.html
> +      <p class="para">Here at the NhCommunity we like to have some fun! We are often working on a handful of projects to improve our community as a whole, that everyone is welcome to contribute to.</
```suggestion
      <p class="para">Here at the nhcommunity we like to have some fun! We are often working on a handful of projects to improve our community as a whole, that everyone is welcome to contribute to.</p>
```

2021-06-03 15:58 UTC, DennaGrey submitted a review, later dismissed
Just a tiny grammar thing :)

2021-06-03 17:23 UTC, Skyhero-admin commented on index.html
> +      <p class="para">Here at the NhCommunity we like to have some fun! We are often working on a handful of projects to improve our community as a whole, that everyone is welcome to contribute to.</
ohh
I will fix it

2021-06-07 13:39 UTC, nhcarrigan approved these changes
This looks good, and has been open for a while. Landing it.

2021-06-07 13:39 UTC, merged